### ISSUE TITLE
error: comparison between 'lcd_color_rgb_endian_t' and 'enum <anonymous>' [-Werror=enum-compare]

### ISSUE THREAD

**Issue by greenhand520** [atanisoft/esp_lcd_ili9488#1]
idf.py build或者CLion构建，相同错误：
> esp_lcd_ili9488.c: In function 'esp_lcd_new_panel_ili9488':
～/Workspace/Projects/CLionProjects/VisualInfo/managed_components/atanisoft__esp_lcd_ili9488/esp_lcd_ili9488.c:349:39: error: comparison between 'lcd_color_rgb_endian_t' and 'enum <anonymous>' [-Werror=enum-compare]
  349 |     if (panel_dev_config->color_space == ESP_LCD_COLOR_SPACE_RGB)
      |                                       ^~
cc1: some warnings being treated as errors
[866/1054] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/manager.c.obj
ninja: build stopped: subcommand failed.

![image](https://user-images.githubusercontent.com/32732204/201086390-855e52e3-c8bd-4326-ba19-fc48cb6607b0.png)

**Comment by atanisoft** [comment]
I wasn't seeing this with v4.4.3 in my tests but it looks to be an easy fix. Was there a specific sdkconfig entry you enabled to trigger this?
