### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by qombajn** [atanisoft/esp_lcd_ili9488#10]
How can I use this? I download this repo and should it compile as it is?

**Comment by atanisoft** [comment]
This is an ESP-IDF component, it will not compile on it's own. It can be compiled by setting up an ESP-IDF build environment and including this component in your project. The example application can be compiled with minimal modifications in ESP-IDF v4.4 or later.

**Comment by qombajn** [comment]
I want to do project on esp32 + ili9488 using esp-idf and lvgl. Can you help and tell me how to show anything on that screen using esp-idf? I opened spi_lcd_touch example and i should import this component to make it work? What is the easiest way to do that kind of project?

**Comment by atanisoft** [comment]
The easiest way to integrate this component with your ESP-IDF project would be to run `idf.py add-dependency atanisoft/esp_lcd_ili9488` and ESP-IDF will take care of the rest. In your project you would then initialize the display and LVGL and it should just work. I'd also suggest using `idf.py add-dependency espressif/esp_lvgl_port` which provides a few helpers for LVGL within an ESP-IDF project.
