### ISSUE TITLE
about use i8080 display ili9488

### ISSUE THREAD

**Issue by meibao-real** [atanisoft/esp_lcd_ili9488#11]
hello ,i have esp32s3 boare i use esp-idf example [lcd/lvgl] by ESP-IDF V4.4.4, Then I incloud "esp_lcd_ili9488.h" and changed 136 lines,
`ESP_ERROR_CHECK(esp_lcd_new_panel_ili9488(io_handle, &panel_config, LCD_H_RES * 20 * sizeof(lv_color_t), true, &panel_handle));`
The pins are modified in the code based on the actual connection, 
```
   ESP Board                      LCD Screen
┌─────────────┐              ┌────────────────┐
│             │              │                │
│         3V3 ├─────────────►│ VCC            │
│             │              │                │
│         GND ├──────────────┤ GND            │
│             │              │                │
│  DATA[0..7] │◄────────────►│ DATA[0..7]     │
│             │              │                │
│        IO12 ├─────────────►│ PCLK           │
│             │              │                │
│        IO10 ├─────────────►│ CS             │
│             │              │                │
│        IO14 ├─────────────►│ D/C            │
│             │              │                │
│         IO9 ├─────────────►│ RST            │
│             │              │                │
│        IO46 ├─────────────►│ BCKL           │
│             │              │                │
└─────────────┘              └────────────────┘
```
```
#define EXAMPLE_PIN_NUM_DATA0          4
#define EXAMPLE_PIN_NUM_DATA1          5
#define EXAMPLE_PIN_NUM_DATA2          6
#define EXAMPLE_PIN_NUM_DATA3          7
#define EXAMPLE_PIN_NUM_DATA4          15
#define EXAMPLE_PIN_NUM_DATA5          16
#define EXAMPLE_PIN_NUM_DATA6          18
#define EXAMPLE_PIN_NUM_DATA7          18
```
but when Build and Flash project, the lcd notwork, , except the backlight is on, and nothing else happens, I mean it looks like it's just the IO46 pin because the high level turns on the backlight, 
So how to use it in the I8080 interface ? 
Please give me some Pointers if you can, thank u very much

**Comment by atanisoft** [comment]
Aside from:
```
#define EXAMPLE_PIN_NUM_DATA6          18
#define EXAMPLE_PIN_NUM_DATA7          18
```
I don't see anything too abnormal in what you have provided.

I haven't tested i8080 mode in some time but it was tested by one of the Espressif devs prior to publishing on the IDF component manager. The example app in this repos is primarily targeting three wire SPI mode, but using [this](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/lcd/i80_controller/main/i80_controller_example_main.c#L157-L207) code for creation of the io_panel it should work.

One note on connecting the data pins to the display, make sure you have the interface type set correctly via the IM{0-2} pins. Also make sure to set up for 16-bit color mode since the i8080 mode supports 16-bit color mode but the three wire SPI mode requires 18-bit.

**Comment by meibao-real** [comment]
> Aside from:
> 
> ```
> #define EXAMPLE_PIN_NUM_DATA6          18
> #define EXAMPLE_PIN_NUM_DATA7          18
> ```
> 
> I don't see anything too abnormal in what you have provided.
> 
> I haven't tested i8080 mode in some time but it was tested by one of the Espressif devs prior to publishing on the IDF component manager. The example app in this repos is primarily targeting three wire SPI mode, but using [this](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/lcd/i80_controller/main/i80_controller_example_main.c#L157-L207) code for creation of the io_panel it should work.
> 
> One note on connecting the data pins to the display, make sure you have the interface type set correctly via the IM{0-2} pins. Also make sure to set up for 16-bit color mode since the i8080 mode supports 16-bit color mode but the three wire SPI mode requires 18-bit.

```
#define EXAMPLE_PIN_NUM_DATA6          18
#define EXAMPLE_PIN_NUM_DATA7          18
````
oh, sorry This is my input error, the actual project configuration is correct.
Reference [this](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/lcd/i80_controller/main/i80_controller_example_main.c#L157-L207) Now ILI9488 is work by i8080 interface, but the fps is very low(10~15) guess there are other problems, after the optimization is complete, I will submit a PR for i8080 example ~~
Thanks a lot

**Comment by atanisoft** [comment]
> after the optimization is complete, I will submit a PR for i8080 example

That may depend on a few factors, mostly on the FreeRTOS tick frequency likely. Give it a test with 1000 as tick frequency, default is 100. It may be causing some unintentional delays in LVGL updates.

Also looking forward to the PR with i8080 example.
