### ISSUE TITLE
ESP32-S3 pins issue

### ISSUE THREAD

**Issue by fivdi** [atanisoft/esp_lcd_ili9488#4]
The [README for the example](https://github.com/atanisoft/esp_lcd_ili9488/blob/v1.0.5/examples/lvgl/README.md), mentions that the ESP32-S3 pins are as follows:
| pin | usage |
| --- | ----- |
| SPI MISO | 13 |
| SPI MOSI | 15 |
| SPI CLK | 14 |
| TFT CS | 3 |
| TFT DC | 9 |
| TFT Backlight | 12 |

However in [Kconfig.projbuild](https://github.com/atanisoft/esp_lcd_ili9488/blob/v1.0.5/examples/lvgl/main/Kconfig.projbuild) the defaults for the ESP32-S3 are defined as follows:
| pin | usage |
| --- | ----- |
| SPI MISO | 13 |
| SPI MOSI | 10 |
| SPI CLK | 11 |
| TFT CS | 3 |
| TFT RESET | 46 |
| TFT DC | 9 |
| TFT Backlight | 12 |

`SPI MOSI` and `SPI CLK` don't match in the tables and there is no mention of `TFT_RESET` in the documentation.

When tyring out esp_lcd_ili9488, I built a circuit and connected everything up as described in the documentation and it didn't work. It took a while to figure out what was going wrong. Maybe it would be a good idea to fix the documentation so that it matched what's in Kconfig.projbuild.

**Comment by atanisoft** [comment]
Fixed as part of v1.0.6.

**Comment by fivdi** [comment]
> Fixed as part of v1.0.6.

Excellent.
