### ISSUE TITLE
spi_mode configured incorrectly

### ISSUE THREAD

**Issue by fivdi** [atanisoft/esp_lcd_ili9488#5]
In the example, `spi_mode` is configured as a pin number [like this](https://github.com/atanisoft/esp_lcd_ili9488/blob/v1.0.5/examples/lvgl/main/main.c#L164):
```c
        .spi_mode = CONFIG_TFT_DC_PIN,
```
`spi_mode` should be configured to a traditional SPI mode (0~3). The correct mode on the display that I have is 0.

**Comment by atanisoft** [comment]
Good catch, not sure why this didn't cause any issues with the example in my tests but it should certainly be corrected.

**Comment by atanisoft** [comment]
Fixed as part of v1.0.6.

**Comment by fivdi** [comment]
> not sure why this didn't cause any issues with the example in my tests

I wondered the same. Thank you for the fix.
